### ISSUE TITLE
Random Cloudflare error 520

### ISSUE THREAD

**Issue by bibicadotnet** [ArtalkJS/Artalk#646]
![2023-11-18_22-24-47](https://github.com/ArtalkJS/Artalk/assets/119997727/e881d38b-faab-48a2-a248-bfba61c849c5)

After using Artalk daily, my site often gets error 520 from Cloudflare. I guess the problem is due to Artalk because I have never encountered this error before.

**Update:**
Not 100% sure, but it seems the error appeared after I added Artalk LightBox

`<script src="/data/artalk-plugin-lightbox.js"></script>`

**Comment by qwqcode** [comment]
Front-end content generally doesn't cause a server-side 520 error, and if it's a static web page, it's even less likely. It might not be an issue related to Artalk.

Could you provide more information, such as web server logs, to help we better troubleshoot the problem? 🤔

**Comment by bibicadotnet** [comment]
Well, I don't really understand, because I've never encountered error 520 before

Mainly based on timing, after adding the artalk-plugin-lightbox.js script this morning, in the afternoon I occasionally got error 520 from Cloudflare, before I updated the artalk-plugin-lightbox configuration there was no problem. no matter

It just shows an error, and after I F5 again the browser works normally

I looked in the Caddy and Artalk logs and saw so much information appearing, I didn't know where to check

**Comment by qwqcode** [comment]
Your blog uses WordPress. Have you made any modifications to the blog theme? I'm just speculating; for instance, when using 'new Artalk,' does it call certain PHP functions? Could you check this aspect for issues within the WordPress program's individual logs? Since it's an intermittent problem, it might be related to a particular WordPress plugin or perhaps a network connectivity issue. Error 520 seems to be related to a CDN reverse proxy error rather than a program error.  Have you deployed any additional web servers for reverse proxy or made configuration changes? 🤔️

**Comment by bibicadotnet** [comment]
Yes, the error is quite confusing, because I tried ArtalkJS for about 7 days and did not see any errors related to Cloudflare

Just this morning, after customizing Artalk LightBox, in the afternoon I saw a random error 520 related to Cloudflare.

I just turned off Artalk LightBox, but after a few hours I don't see that error anymore :(

I also think the error is due to a problem with the reverse proxy configuration from Caddy, but I'm currently using Cloudflare Tunnels, so I'm not too sure.

Currently, I have not seen the error again, maybe I will close this issue, then update the situation later

**Comment by bibicadotnet** [comment]
After a period of testing, the error is not from Artalk's side but seems to be due to a plugin I am using on WordPress.
