### ISSUE TITLE
2.7.1 为什么没有之前那种嵌套评论了，回复的评论和新评论一样显示了。

### ISSUE THREAD

**Issue by dianso** [ArtalkJS/Artalk#677]
2.7.1 为什么没有之前那种嵌套评论了，回复的评论和新评论一样显示了。

**Comment by dianso** [comment]
还是以前那种比较直观

**Comment by bibicadotnet** [comment]
具体在这里 [Flatten mode true and false infected](https://github.com/ArtalkJS/Artalk/issues/671)

使用“auto”临时修复

**Comment by dianso** [comment]
> 具体在这里 [Flatten mode true and false infected](https://github.com/ArtalkJS/Artalk/issues/671)
> 
> 使用“auto”临时修复

感谢回复，果然有效！

**Comment by bibicadotnet** [comment]
“自动”模式仅对平板电脑和 PC 等大屏幕设备有暂时的影响，对于手机等小型设备，它将采用“Flatten mode = true”格式

**Comment by qwqcode** [comment]
这是个 BUG，刚已经修复了，错误原因是：类型为 Boolean 的开关被错误转换为了字符串。临时修复的办法可以在配置文件手动修改 `"true"` 为 `true`。

---

This is a bug that has just been fixed.

The issue was caused by a Boolean-type switch being incorrectly converted to a string.

A temporary fix would be to manually change `"true"` to `true` in the `artalk.yaml` configuration file.

感谢反馈！❤️

**Comment by qwqcode** [comment]
新版 v2.7.2 已发布，包括了这个问题的修复 😀

---

The new version v2.7.2 has been released, which includes a fix for this issue.
