### ISSUE TITLE
Some tweaks related to Frontend cookies

### ISSUE THREAD

**Issue by bibicadotnet** [ArtalkJS/Artalk#695]
![403398470_931288158576496_3255160621438798079_n](https://github.com/ArtalkJS/Artalk/assets/119997727/d37b2f27-ab52-4356-9f9a-77d4617c728e)
By default Artalk manages versions according to version configuration

`https://cdnjs.cloudflare.com/ajax/libs/artalk/**2.7.1**/Artalk.js`
`https://cdnjs.cloudflare.com/ajax/libs/artalk/**2.7.1**/Artalk.css`

Every time there is a new version, there will be a different link

`http://your_domain:8080/dist/Artalk.css`
`http://your_domain:8080/dist/Artalk.js`

It will keep the link intact regardless of version

The actual situation that happened was when I updated Artalk to a new version

Almost all old members will see a message like the one in the picture

I'm currently handling it the same way

`https://bibica.net/Artalk/2.7.1/Artalk.css`
`https://bibica.net/Artalk/2.7.1/Artalk.js`

It's a bit annoying because now every time I update a new version, I will have to recreate these two files

Is there a simpler way to handle this problem?

**Comment by qwqcode** [comment]
Hello! If you're utilizing Cloudflare, you can utilize the [Purge by single-file (by URL)](https://developers.cloudflare.com/cache/how-to/purge-cache/purge-by-single-file/) feature. This allows for manual refreshing of the CDN cache remotely via the Cloudflare web control page, effectively applying changes locally on the client's end. Essentially, this action can modify the HTTP response headers such as Last-Modified and If-Modified-Since, consequently refreshing client caches remotely.

For more in-depth technical insights, you can explore:

[Heuristic caching on MDN Web Docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching#heuristic_caching)

Alternatively, for those not using a CDN service like Cloudflare, a simple solution involves configuring your Nginx reverse proxy. Ensure that the response header for the dist path consistently carries Cache-Control: no-cache. This setup effectively prevents client-side caching.

**Comment by bibicadotnet** [comment]
重新计算后，我认为我们仍然应该使用与我们正在使用的CDN服务相同的方法

默认值仍然是无限缓存“expires max;”，以优化用户性能。

稍后，当有新版本时，我会手动将其更新到另一个文件夹，例如`https://bibica.net/Artalk/2.7.2/`

不需要花太多时间，大多数情况下我有时会忘记它
