### ISSUE TITLE
If the `FlatMode` is disabled, the reply will be hidden in the `GET /comments`

### ISSUE THREAD

**Issue by syhily** [ArtalkJS/Artalk#891]
I think the [commit](https://github.com/ArtalkJS/Artalk/commit/c2c5a80d8d3cf9eead4817fff7749203a9a63495) introduce this bug.

After comment [the line](https://github.com/ArtalkJS/Artalk/blob/1e36d45ec356188fe8f3e321520d6d820b3a6738/server/handler/comments_get/expose.go#L32), everything works as expected.

As I debug further into the code. I found that when I was using the Postgres of MySQL with Artalk, the RootID will be NULL by default. This will make `findNestedChildren` method buggy.

**Comment by syhily** [comment]
Ok, I was trying to generate the root_id by enabling the `ATK_DB_MIGRATOR_FUNC_MIGRATE_ROOT_ID=1`.

**Comment by syhily** [comment]
Ok, I think the force generate the Root ID solved my problems.

**Comment by qwqcode** [comment]
这个可能是 root_id 没有正确生成导致的问题（相关：#848 #846 #833），可以检查 comments 表中 root_id 列是否全为 0，如果 root_id 不正确可以尝试在 artalk 启动前增加环境变量 ATK_DB_MIGRATOR_FUNC_MIGRATE_ROOT_ID=1 重新生成 root_id。

root_id 是用于缓存评论树叶子节点往上的最顶层根节点 ID，缓存递归查询结果提高性能

---

This issue may be caused by the incorrect generation of root_id (related: #848 #846 #833). You can check if the root_id column in the comments table is all set to 0. If root_id is incorrect, you can try adding the environment variable ATK_DB_MIGRATOR_FUNC_MIGRATE_ROOT_ID=1 before starting artalk to regenerate root_id.

root_id is used to cache the ID of the top-level root node upwards from the leaf nodes of the comment tree, caching recursive query results to improve performance.

**Comment by qwqcode** [comment]
> Ok, I think the force generate the Root ID solved my problems.

Alright, I got it. You've solved it already! :)

**Comment by syhily** [comment]
@qwqcode Yep, you are right. After reading your code and debug locally. I found that it was caused by the missing root id. But I didn't meet the comments listing issues until you have migrated the query logic to `root_id`. 

Given that I can't find any documentation that describe the `ATK_DB_MIGRATOR_FUNC_MIGRATE_ROOT_ID ` and you are working on code refactoring with heavily changed database schema. I sincerely asked if you can add a troubleshooting document to mention these potential regressions.

**Comment by qwqcode** [comment]
I'm sorry, you're right. I should have added some documentation to address this issue, but I've been too busy lately. I missed some pre-release testing in v2.8.5 and overlooked the fact that some older databases don't support SQL recursive CTE and not providing a fallback solution. This resulted in root_id not being generated correctly for some users upgrading to v2.8.5. However, this issue should have been fixed in v2.8.6. My intention was to make these changes to the data structure and upgrades seamless and automatic.

**Comment by syhily** [comment]
Haha, I see. I'm not mean to complain. BTW, this regression didn't get solved in 2.8.6 if the `root_id` didn't get properly generated. And the start up hangs for a long time, if I have too much comments. I think we have better to use a go routine to generate the `root_id`.

Thanks your great works.
